---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: basicapps.platform.upbound.io
spec:
  group: platform.upbound.io
  scope: Namespaced
  names:
    categories:
      - crossplane
    kind: BasicApp
    plural: basicapps
  versions:
    - name: v1
      referenceable: true
      schema:
        openAPIV3Schema:
          description: BasicApp is a simple example showing direct Kubernetes resource mapping.
          properties:
            spec:
              description: BasicAppSpec defines the desired state of BasicApp.
              properties:
                parameters:
                  properties:
                    name:
                      description: Name for the resources
                      type: string
                    image:
                      description: Container image configuration
                      properties:
                        repository:
                          type: string
                        tag:
                          type: string
                        pullPolicy:
                          type: string
                      type: object
                    pod:
                      description: Pod/Deployment configuration
                      properties:
                        replicaCount:
                          type: integer
                        resources:
                          properties:
                            limits:
                              additionalProperties:
                                type: string
                              type: object
                            requests:
                              additionalProperties:
                                type: string
                              type: object
                          type: object
                        securityContext:
                          properties:
                            capabilities:
                              properties:
                                drop:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            readOnlyRootFilesystem:
                              type: boolean
                            runAsNonRoot:
                              type: boolean
                            runAsUser:
                              type: integer
                          type: object
                        podSecurityContext:
                          properties:
                            fsGroup:
                              type: integer
                          type: object
                      type: object
                    service:
                      description: Service configuration
                      properties:
                        enabled:
                          type: boolean
                        type:
                          type: string
                        port:
                          type: integer
                      type: object
                    ingress:
                      description: Ingress configuration
                      properties:
                        enabled:
                          type: boolean
                        className:
                          type: string
                        annotations:
                          additionalProperties:
                            type: string
                          type: object
                        hosts:
                          items:
                            properties:
                              host:
                                type: string
                              paths:
                                items:
                                  properties:
                                    path:
                                      type: string
                                    pathType:
                                      type: string
                                  type: object
                                type: array
                            type: object
                          type: array
                      type: object
                    serviceAccount:
                      description: ServiceAccount configuration
                      properties:
                        enabled:
                          type: boolean
                        name:
                          type: string
                        annotations:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                  type: object
              type: object
            status:
              description: BasicAppStatus defines the observed state.
              type: object
          required:
            - spec
          type: object
      served: true
