apiVersion: platform.upbound.io/v1
kind: BasicApp
metadata:
  name: example
  namespace: default
spec:
  parameters:
    name: app1
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "latest"

    serviceAccount:
      enabled: true
      name: "app1"
      # Annotations to add to the service account
      # annotations: {}

    pod:
      replicaCount: 1
      # podSecurityContext: {}
      #   fsGroup: 2000
      # securityContext: {}
      #   capabilities:
      #     drop:
      #     - ALL
      #   readOnlyRootFilesystem: true
      #   runAsNonRoot: true
      #   runAsUser: 1000
      # resources: {}
      #   limits:
      #     cpu: 100m
      #     memory: 128Mi
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi

    service:
      enabled: true
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      # className: ""
      # annotations: {}
      #   kubernetes.io/ingress.class: nginx
      #   kubernetes.io/tls-acme: "true"
      # hosts:
      #   - host: chart-example.local
      #     paths:
      #       - path: /
      #         pathType: ImplementationSpecific
